spring.application.name=GitHub-actions-test1
cluster.address=cluster0.ofvi4ed.mongodb.net
dbuser=harshkhurana337_db_user
dbpassword=cXdzkacw1PTQPhNl
dbName=mongodb
spring.data.mongodb.uri=mongodb+srv://${dbuser}:${dbpassword}@${cluster.address}/${dbName}?retryWrites=true&w=majority
