spring.application.name=GitHub-actions-test1
cluster.address=process.env.MONGODB_CLUSTER
dbuser=process.env.MONGODB_USER
dbpassword=process.env.MONGODB_PASSWORD
dbName=process.env.MONGODB_DATABASE
spring.data.mongodb.uri=mongodb+srv://${dbuser}:${dbpassword}@${cluster.address}/${dbName}?retryWrites=true&w=majority
