name: installing and caching dependencies
description: This action installs and caches dependencies for a Maven project.
inputs:
  java-version:
    description: 'Java version to set up'
    required: true
    default: '26'
  distribution:
    description: 'Java distribution to use (e.g., temurin, zulu, etc.)'
    required: true
    default: 'temurin'
  cache:
    description: 'Whether to cache Maven dependencies (true/false)'
    required: true
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Set up Java and Maven Cache
      uses: actions/setup-java@v6
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        # If cache input is 'true', pass 'maven' to setup-java, otherwise pass an empty string to disable it
        cache: ${{ inputs.cache == 'true' && 'maven' || '' }}
