name: installing and caching dependencies
description: This action installs and caches dependencies for a Maven project.
inputs:
  java-version:
    description: 'Java version to set up'
    required: true
    default: '21'
  distribution:
    description: 'Java distribution to use (e.g., temurin, zulu, etc.)'
    required: true
    default: 'temurin'
  cache:
    description: 'Whether to cache Maven dependencies (true/false)'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Set up Java and Maven Cache
      uses: actions/setup-java@v6
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
    - name: caching the dependencies
      if: ${{ inputs.cache == 'true' }}
      id: cache-deps
      uses: actions/cache@v6
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
